#!/usr/bin/env python2

import sys

from PyQt4 import QtGui

from ratingWidget import RatingWidget


class MainWindow(QtGui.QMainWindow):
    def __init__(self):
        super(MainWindow, self).__init__()
        central_widget = RatingWidget()
        self.setCentralWidget(central_widget)


if __name__ == '__main__':
    app = QtGui.QApplication(sys.argv)
    app.setStyle('Cleanlooks')
    main_window =  MainWindow()
    main_window.show()
    sys.exit(app.exec_())

